package genericframes.helperframes;


import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import mediaplayer.MediaPlayer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * Message Frame show the Error generated by Users. It displays the Error type and the massage show user a message of
 * where exactly the error occurred. Error types are listed below:
 * ERROR 1 :blank fields, no name entered
 * ERROR 2 :illegal file- file does not exist a) video file b) mp3 file
 * ERROR 3 :illegal file- file is a directory a) video file b) mp3 file
 * ERROR 4 :no file has been selected.
 * ERROR 5 :try to create an exist file
 * ERROR 6 :this is not a directory
 * ERROR 7 :invalid name.
 * ERROR 9 :illegal start time.
 */
public class MessageFrame extends JFrame {

	private JPanel contentPane;
	private JFrame thisFrame = this;
	private JLabel errorLabel = new JLabel();
	private final ImageIcon ErrorIcon1 = new ImageIcon(
			MediaPlayer.class.getResource("/javagui/resources/Error1.png"));
	
	/**
	 * Constructor which allows you to construct simple user prompts 
	 * @param x
	 * @param y
	 * @param frameTitle	title of the frame
	 * @param messageTitle	title of the message
	 * @param messageText	the message to the user
	 */
	public MessageFrame(int x,int y,String frameTitle, String messageTitle, String messageText) {
		
		//setup the frame
		setBounds(x, y, 320, 120);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		thisFrame.setTitle(frameTitle);
		thisFrame.setResizable(false);
		thisFrame.setUndecorated(true);
		thisFrame.setOpacity(0.6F);
		thisFrame.setBackground(new Color(255,255,255));
		contentPane.setBackground(new Color(255,255,255));
		contentPane.setLayout(null);
		
		// title of the message
		errorLabel.setFont(new Font("Dialog", Font.BOLD, 18));
		errorLabel.setBounds(10, 5, 200, 60);
		errorLabel.setIcon(ErrorIcon1);
		errorLabel.setForeground(Color.RED);
		errorLabel.setText(messageTitle);
		contentPane.add(errorLabel);
		
		//message to give to user
		JLabel message = new JLabel(messageText);
		message.setBounds(10, 50, 300, 30);
		contentPane.add(message);
		
		JButton okButton = new JButton("OK");
		okButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				thisFrame.dispose();
			}
		});
		okButton.setBounds(110, 90, 100, 25);
		contentPane.add(okButton);
	}
	
	/**
	 * Get the error type
	 * @return
	 */
	public String getErrorTile(){
		return this.errorLabel.getText();
	}
	
}
